In [2]:
import numpy as np
lst=[2,34,34,3,54,5,4,65]
q=np.array(lst)
q

array([ 2, 34, 34,  3, 54,  5,  4, 65])

In [4]:
tp=(43,534,5,43,6,546,54,6,456,456,45)
t=np.array(tp)
t

array([ 43, 534,   5,  43,   6, 546,  54,   6, 456, 456,  45])

In [7]:
w=np.asarray(tp)
w

array([ 43, 534,   5,  43,   6, 546,  54,   6, 456, 456,  45])

In [8]:
s=np.arange(0,10)
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
f=np.ones((3,4))
f

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
g=np.ones_like(s)
g

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [13]:
z=np.zeros(9)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
x=np.zeros_like(f)
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
v=np.empty_like(x)
v

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
m=np.full_like(v,87)
m


array([[87., 87., 87., 87.],
       [87., 87., 87., 87.],
       [87., 87., 87., 87.]])